name: "Check PR Label"

on:
  workflow_call:
    inputs:
      label:
        description: "The label name that should block the PR"
        required: true
        type: string

jobs:
  fail-if-label-exists:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR has the label
        if: contains(fromJson('["opened", "labeled", "unlabeled"]'), github.event.action)
        run: |
          LABELS=$(jq -r '.pull_request.labels[].name' "$GITHUB_EVENT_PATH")
          if echo "$LABELS" | grep -q "${{ inputs.label }}"; then
            echo "This PR has the label '${{ inputs.label }}'. Merge is blocked."
            exit 1
          fi
