name: Check Required Changes

on:
  workflow_call:
    inputs:
      pr_description:
        description: "Pull request description"
        required: true
        type: string

jobs:
  check-pr-description:
    runs-on: ubuntu-latest
    steps:
      - name: Extract checked required changes
        id: extract_checked
        run: |
          echo "Extracting checked required changes..."
          CHECKED_ITEMS=$(echo "${{ inputs.pr_description }}" | awk '/## Required changes/{flag=1; next} /^##/{flag=0} flag' | grep '^\s*- \[x\] ' | sed 's/- \[x\] //')

          if [[ -z "$CHECKED_ITEMS" ]]; then
            echo "✅ No checked required changes found."
            exit 0
          fi

          echo "CHECKED_ITEMS<<EOF" >> $GITHUB_ENV
          echo "$CHECKED_ITEMS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check for non-PR required changes
        run: |
          echo "Checking for non-PR items..."
          while IFS= read -r ITEM; do
            if [[ ! "$ITEM" =~ ^(https://github\.com/[^/]+/[^/]+/pull/[0-9]+|#[0-9]+)$ ]]; then
              echo "❌ Required change is checked but is not a valid PR reference: '$ITEM'"
              exit 1
            fi
          done <<< "$CHECKED_ITEMS"

      - name: Check if required PRs are merged
        if: success()
        run: |
          echo "Checking if PRs are merged..."
          while IFS= read -r ITEM; do
            # If the item is a full PR link, extract the PR number
            if [[ "$ITEM" =~ ^https://github\.com/[^/]+/[^/]+/pull/([0-9]+)$ ]]; then
              PR_NUMBER="${BASH_REMATCH[1]}"
            # If it's just a PR number (e.g., #123), use it directly
            elif [[ "$ITEM" =~ ^#[0-9]+$ ]]; then
              PR_NUMBER="${ITEM//#/}"
            fi

            echo "Checking PR #$PR_NUMBER..."
            PR_RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER")

            # Log the full response for debugging
            echo "PR Response: $PR_RESPONSE"

            # Check for merged status
            MERGED=$(echo "$PR_RESPONSE" | jq -r '.merged')

            if [[ "$MERGED" != "true" ]]; then
              echo "❌ PR #$PR_NUMBER is not merged. Required changes are incomplete."
              exit 1
            fi
          done <<< "$CHECKED_ITEMS"

          echo "✅ All required PRs are merged."
